### ISSUE TITLE
Looking for DataSets

### ISSUE THREAD

**Issue by Samim772** [MIT-Emerging-Talent/2024-group-04-cdsp#3]
Each of us will search for raw data sets in the healthcare industry and present them with some research questions on coming Sunday.

**Comment by Samim772** [comment]
**About Dataset**

Healthcare Patient Satisfaction - Data Collection

In the U.S., every hospital that receives payments from Medicare and Medicaid is mandated to provide quality data to The Centers for Medicare and Medicaid Services (CMS) annually. This data helps gauge patient satisfaction levels across the country. While overall hospital scores can be influenced by the quality of customer services, there may also be variations in satisfaction based on the type of hospital or its location.

Year: 2016 - 2020

The Star Rating Program, implemented by The Centers for Medicare & Medicaid Services (CMS), employs a five-star grading system to evaluate the experiences of Medicare beneficiaries with their respective health plans and the overall healthcare system. Health plans receive scores ranging from 1 to 5 stars, with 5 stars denoting the highest quality.

Benefits:

Historical Analysis: With data spanning from 2016 to 2020, researchers and analysts can observe trends over time, understanding how patient satisfaction has evolved over these years.

Benchmarking: Hospitals can compare their performance against national averages or against peer institutions to see where they stand.

Identifying Areas for Improvement: By analyzing specific metrics and feedback, hospitals can pinpoint areas where their services may be lacking and need enhancement.

Policy and Decision Making: Governments and healthcare administrators can use the data to make informed decisions about healthcare policies, funding allocations, and other strategic decisions.

Research and Academic Purposes: Academics and researchers can use the dataset for various studies, including correlational studies, predictions, and more.

Geographical Insights: The dataset may provide insights into regional variations in patient satisfaction, helping to identify areas or states with particularly high or low scores.

Understanding Factors Affecting Satisfaction: By correlating satisfaction scores with other variables (e.g., hospital type, size, location), it might be possible to determine which factors play the most significant role in patient satisfaction.

Performance Evaluation: Hospitals can use the data to evaluate the efficacy of any interventions or changes they've made over the years in terms of improving patient satisfaction.

Enhancing Patient Trust: Demonstrating transparency and a commitment to improvement can enhance patient trust and loyalty.

Informed Patients: By making such data publicly available, potential patients can make more informed decisions about where to seek care based on the satisfaction ratings of previous patients.

Source: https://data.cms.gov/provider-data/archived-data/hospitals


https://www.kaggle.com/datasets/kaggleprollc/healthcare-patient-satisfaction-data-collection

**Comment by Samim772** [comment]
**Some research questions about Healthcare Patient Satisfaction:**

Here are some research questions that could be explored using the Healthcare Patient Satisfaction dataset:

1. How has patient satisfaction with hospitals evolved from 2016 to 2020? Are there any noticeable trends or patterns over this period?

2. What are the key factors influencing patient satisfaction with healthcare services? Can demographic variables such as age, gender, or ethnicity be correlated with satisfaction scores?

3. Do certain types of hospitals (e.g., teaching hospitals, rural hospitals) consistently perform better or worse in terms of patient satisfaction compared to others?

4. How do regional variations in healthcare delivery impact patient satisfaction levels? Are there geographical areas with consistently higher or lower satisfaction scores?

5. What specific aspects of hospital care contribute most to overall patient satisfaction? For example, are communication with healthcare providers, waiting times, or cleanliness of facilities significant factors?

6. How do different healthcare policies and interventions implemented by hospitals affect patient satisfaction scores over time?

7. Can patient satisfaction scores be used as indicators of healthcare quality and performance? How do they correlate with other measures such as mortality rates or readmission rates?

8. Are there disparities in patient satisfaction based on insurance status or socioeconomic factors? Do patients with different insurance types or income levels report different levels of satisfaction?

9. How do hospitals with higher patient satisfaction scores compare in terms of financial performance and reputation compared to those with lower scores?

10. What strategies can hospitals employ to improve patient satisfaction and enhance overall healthcare quality? Are there best practices that can be identified from hospitals with consistently high satisfaction scores?

These research questions can serve as a starting point for exploring the Healthcare Patient Satisfaction dataset and uncovering valuable insights into patient experiences and healthcare delivery.

**Comment by mahdig7** [comment]
Hi everyone,
These are the two datasets I would like us to work on:
1) Heart disease 2) Suicide rate

Questions for suicide dataset:
1. How has the global suicide trend evolved from 1985 to 2016?
2. How have the trends in sex-based suicide rates evolved over the years?
3. What are the trends in suicide rates across different age groups over time?
4. What are the gender differences in suicide rates across different age groups?
5. What is the impact of generational differences on suicide rates over time?
6. How does the total number of suicides differ between males and females from 1985 to 2015?
7. What are the top 10 countries with the highest suicide rates?
8. Which countries have the lowest suicide rate?
9. What is the correlation between GDP per capita and suicide rates among males and females across different countries, and how does this correlation differ between genders?
10. Which are the top 4 countries with the highest suicide rates, and their trend over the years?
11. How did the average suicide rate in the United States change before and after the Great Recession of 2008 (during the years 2005-2010)?


Questions for heart diseases:
1. How does the distribution of ages differ among individuals who experienced a heart disease compared to those who did not?
2. What is the probability and distribution of heart disease occurrences among different genders?
3. How does the distribution of different types of chest pain vary among individuals who experienced a heart disease?
4. How does the distribution of the number of major vessels detected vary across different age groups?
5. How does blood pressure within the normal range (around 80 mm Hg) compare to higher blood pressure in relation to the likelihood of experiencing a heart disease?
6. Does having cholesterol levels within the range of 125-200 mg/dL affect the probability of experiencing a heart disease compared to individuals with higher or lower cholesterol levels?
7. How does the distribution of maximum heart rates achieved differ between individuals who experienced a heart disease and those who did not?
8. How does age correlate with other heart disease variables?
9. How does the distribution of heart ST depression levels differ between individuals who experienced a heart disease and those who did not?


[master.csv](https://github.com/MIT-Emerging-Talent/2024-group-04-cdsp/files/14232717/master.csv)
[heart.csv](https://github.com/MIT-Emerging-Talent/2024-group-04-cdsp/files/14232719/heart.csv)

**Comment by sediqem** [comment]
The rate of suicide rate between 2009-2020 in states of the USA based on race.
https://opendata.maryland.gov/api/views/8kn6-62x4/rows.csv?accessType=DOWNLOAD
Question:
1. which state has the highest rate of suicide?
2. which state has the lowest rate of suicide rate?
3. which race has the highest rate of suicide?
4. which race has the lowest rate of suicide?

**Comment by sediqem** [comment]
https://data.cdc.gov/api/views/2m93-xvra/rows.csv?accessType=DOWNLOAD
health conditions among children under age 18

**Comment by Han4573** [comment]
Correlation between time spent on social media and mental health?

[smmh.csv](https://github.com/MIT-Emerging-Talent/2024-group-04-cdsp/files/14233626/smmh.csv)

**Comment by MahnazNabizada** [comment]
https://www.kaggle.com/datasets/unitednations/refugee-data?resource=download 
Refugee demographics (demographics.csv)

Questions:
Are there any patterns or trends in the distribution of refugees based on their home countries?
What are the main countries of origin for the refugees in the dataset?
Can we identify the primary destination countries for these refugees?
What is the educational background of the refugee population? (e.g., literacy rates, educational attainment)

**Comment by Han4573** [comment]
The topic correlation between time spent on social media and mental health got more votes so we chose it as our topic
