### ISSUE TITLE
Problem Identification-DataSet Research Questions

### ISSUE THREAD

**Issue by Samim772** [MIT-Emerging-Talent/2024-group-04-cdsp#4]
> Correlation between time spent on social media and mental health?
> 
> [smmh.csv](https://github.com/MIT-Emerging-Talent/2024-group-04-cdsp/files/14233626/smmh.csv)
> 
>  

 _Originally posted by @Han4573 in [#3](https://github.com/MIT-Emerging-Talent/2024-group-04-cdsp/issues/3#issuecomment-1937836141)_

**Comment by Samim772** [comment]
These are my questions regarding to this topic:

1. How does age correlate with the amount of time spent on social media and mental health outcomes?
2. **_Is there a difference in social media usage and its impact on mental health between genders?__**
3. How does relationship status influence the relationship between social media usage and mental health?
4. Do individuals in different occupational statuses experience varying levels of mental health issues related to social media use?
5. What types of organizations are associated with higher levels of social media usage and poorer mental health outcomes?

**Comment by sediqem** [comment]
_**1. Is there any correlation between the time spent on social media and sleep issues?**_
2. Is there any correlation between the time spent on social media and feeling sadness or depression?
3. Is there any correlation between the time spent on social media and comparing him/herself to other people through the use 
   of social media?
4. Is there any correlation between the time spent on social media and difficulty concentrating?
5. Is there any correlation between the time spent on social media and being worried and anxious?
6. Is there any correlation between occupational status and being worried and anxious?

**Comment by MahnazNabizada** [comment]
**_1. How does the frequency of social media use correlate with self-reported levels of stress and anxiety among different age groups?_**
2. Is there a correlation between the type of content consumed on social media (e.g., news, entertainment, social interactions) and reported mental health outcomes?
3. Do individuals who engage in online social comparison through social media platforms experience higher levels of mental health issues compared to those who do not engage in such comparisons?
4. Is there a correlation between the number of social media platforms used simultaneously and the likelihood of experiencing symptoms related to mental health disorders?
5. How does the duration of social media use before bedtime correlate with the prevalence of sleep disturbances and insomnia among users?

**Comment by Zainab-Hussaini** [comment]
1- What is the relationship between concentration difficulties and social media usage?
2- How does daily time spent on social media influence mental health outcomes?
3- How do gender differences impact social media usage and mental health outcomes?
4- How does social comparison on social media impact mental health?
5- How do individuals feel after comparing themselves to others on social media?

**Comment by Han4573** [comment]
**_1 Is there a correlation between time spent on social media and focus problem?
2 How often do university students use social media?_** 
3 on which gender does often usage social media impact mental health more?
4 does the job we do affect the time we spent on social media and mental health?
5 does relationship states affect social media usage and mental health?
